version: "3"
services:
  db-test:
    image: postgres:15
    restart: always
    container_name: go_base-postgres-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_base
    volumes:
      - ./docker/db-test:/var/lib/postgresql/data
  redis-test:
    image: redis:latest
    restart: always
    container_name: go_base-redis-test
    ports:
      - "6380:6379"
    volumes:
      - ./docker/redis:/data
  redis-commander-test:
    container_name: go_base-redis-commander-test
    image: rediscommander/redis-commander:latest
    platform: linux/amd64
    restart: always
    ports:
      - "8090:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
