db:
  host: host.docker.internal # or you need to change to
  port: 5432
  user: changeuserhere # don't forget to change
  password: changepasswordhere # don't forget to change
  dbname: changedbnamehere # don't forget to change
  sslmode: disable
  timezone: Asia/Bangkok
  dbdebug: false

redis:
  host: host.docker.internal:6379 # or you need to change to
  db: 0
  password:
  tlsserver:

userauth:
  applicationname: "base-services"
  bantokenguardthreshold: 300
  jwtsecret: jwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecret
  accesstokenduration: 24h
  refreshtokenduration: 48h
  verifytokenduration: 30m
  accountlockoutmaxattempts: 3
  resendotpmaxattempts: 3
  verifyotpmaxattempts: 3
  lentemppwd: 8

adminauth:
  applicationname: "base-services"
  bantokenguardthreshold: 300
  jwtsecret: jwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecretjwtsecret
  accesstokenduration: 24h
  refreshtokenduration: 48h
  verifytokenduration: 30m
  accountlockoutmaxattempts: 3
  resendotpmaxattempts: 3
  verifyotpmaxattempts: 3
  lentemppwd: 8
